CREATE TABLE LOGIN_TBL(
    MEMBER_NO NUMBER NOT NULL,
    LOGIN_DATE DATE,
    CONSTRAINT FK_MEMBER_LOGIN FOREIGN KEY(MEMBER_NO) REFERENCES MEMBER_TBL(MEMBER_NO) ON DELETE CASCADE
);

CREATE TABLE MEMBER_TBL(
    MEMBER_NO NUMBER NOT NULL,
    ID        VARCHAR2(30 BYTE) NOT NULL,
    PW        VARCHAR2(30 BYTE) NOT NULL,
    NAME      VARCHAR2(30 BYTE),
    PHONE     VARCHAR2(15 BYTE),  
    CONSTRAINT PK_MEMBER PRIMARY KEY(MEMBER_NO)
);


CRAEATE  TABLESPACE MY_SPACE
DATAFILE 'C:/oraclexe/my_space.dbf'
SIZE 10MB;
